name: Deploy Transform Lambda (CSV + pandas)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build Lambda ZIP with pandas
        run: |
          rm -rf lambda_build transform_lambda.zip
          mkdir lambda_build
          pip install pandas -t lambda_build/
          cp ingestion/transform.py lambda_build/
          cd lambda_build && zip -r ../transform_lambda.zip . && cd ..

      - name: Upload ZIP to S3
        run: |
          aws s3 cp transform_lambda.zip s3://lambda-deployments-euc1/transform_lambda.zip

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name data-transform-fn \
            --s3-bucket lambda-deployments-euc1 \
            --s3-key transform_lambda.zip
