name: Deploy Earthquake Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Lambda package with dependencies
        run: |
          mkdir -p lambda_build
          pip install requests -t lambda_build/
          cp ingestion/get_data.py lambda_build/
          cd lambda_build && zip -r ../lambda.zip . && cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name data-ingest-fn \
            --zip-file fileb://lambda.zip
