name: Deploy Transform Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install AWS CLI
        uses: aws-actions/setup-aws-cli@v1

      - name: Download base Lambda zip from S3
        run: |
          aws s3 cp s3://lambda-deployments-euc1/transform_base.zip transform_lambda.zip

      - name: Replace transform.py inside ZIP
        run: |
          unzip transform_lambda.zip -d lambda_temp
          cp ingestion/transform.py lambda_temp/
          cd lambda_temp
          zip -r ../transform_lambda.zip .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Upload updated Lambda package to S3
        run: |
          aws s3 cp transform_lambda.zip s3://lambda-deployments-euc1/transform_lambda.zip

      - name: Deploy to Lambda from S3
        run: |
          aws lambda update-function-code \
            --function-name data-transform-fn \
            --s3-bucket lambda-deployments-euc1 \
            --s3-key transform_lambda.zip
